#!/bin/sh

# Get Multiple Monitors
MAIN=$(xrandr | grep primary | awk '{print $1}')
SECOND=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')

# Configure Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Monitor Handling
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Focus Changing
bspc config focus_follows_pointer true

# Gaps
bspc config window_gap 15
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config gapless_monocle true

# Borders
bspc config border_width 0
bspc config borderless_monocle true

# Full-Screen if one window
bspc config single_monocle true

# Autostart
sxhkd & # Autostart keybinds
picom --experimental-backends & # Compositor
autorandr --change & 
~/.config/fehbg/fehbg.conf & # Background
~/.config/polybar/launch.sh & # Widgets/Bars
redshift & # Night Shift
nm-applet & # Network Manager
